# Terminal
set -g default-terminal "tmux-256color"

set -as terminal-features ",xterm-ghostty:RGB:usstyle"

set -sg escape-time 10
set -g focus-events on


# General
set -g mode-keys vi
set -g history-limit 100000
set -g renumber-windows on
set -g status-position top


# Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"


# Pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R


# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
